language: java

notifications:
  email:
    recipients:
      - dengguiheng@vikadata.com
    on_success: change
    on_failure: always

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - secure: id1UPZpaHY79JMJx/3wvZ2eKiVEDc8z8hLtgZ84kVa16gnh3YTGWfEyZV0Qkbgyck3WNivyuFRiOUZGAz2zXYD3xWGZyGrgXLGxAju8WM4xeUeeqwCkGrZnYszK/hWYEV94Icp3NTtfiECzVTrbPDjWmj37bSPQ8uUl2eg7i0gcnHvjDUC3SF+pvjMUdzpZz1/ULmxriNtbw7gpu0V2AolwTxrRrwdlI9pUfLd0BJB8JHB1kJVeKvgmSaRcQoIo/3CBi/iJXgMLRxBKg3KxLte1fCC8Nca+/jxeDfRSwChzkwtXB2cJ4Wp3I8Kq/VZhpK8t99EhGC9LOfahGf/sWmimeEBL0EM/A/XmAsJeb4WeQkMiH6muk2Sl7aoVNYSJr2WqVh5GwZZ6+5yF5KlKW8kW92vfkR8bi7daAFZagiocOVbllawFqF2hrtT3JTTF/0byGjYh1TkR0XgkcEP7VaBZmjJCZyg0a4t4cmS+4k1u/1SFKgfeZMaYJ7n+WGJiFDtw6E/essbUAlg+21uJMkDP/IbNRqfLj90+V+6qJY37F8l1zjTBoBMHsvDDuK9ycfW4KNp1EsCfyZHm+VvCCeEsw1V83QI3qUWHxEYE+unu1Nb+l85/qZ3BXplfAsbETIDDFmjTScYUZRTOQwFggbQ2SnHVsSujOp6jCZe9qG0Y=
    - secure: DcyoG8jVCMSKtOtZ5ICpB4ONAraJ0vLhglthaX/F9+F6dzqUt6kaDF4uN4g0H0fXUoLwoHTEAzyJjv+WU+5lkry5wY+fAfFao1uP3zdcpmEjwOVfAPnBjibzfLcP7D/KjDHGVyhukjvm+s+FCr4h82Viq20A8XOJnuW26X+bDRHEOi407mM9sK1ukoUykR0xrBngrC6agCWcTNyGIaX/qJMkRRJ3nNy0Zb1vTzWa9OJyp9N1MxUE9uCn3KMi6D6eILdqcWOu3zLei4CPd23EEGuSqVcA+YyLCouK7HM0NnoFzV5QTUsMEjl7by/F7AuYBH2QZpoA3PrMXiGw6C4NJu3NoLlbdNXuX4Ocw3XM25RHUDhQgt1y+9vbHLbf4iUooiHeLqdrJVCkDEYFmWmJcLRfK+eWJjS80/s/P6aFY5Lx6Skxq7bpcNmVDM5TF9hcTTBNjLstzbEF5SmcocDRcVEFr4AbzI04bU2B2MZmTHhY3U09nDfnGNdsFAiySu6Kf7AUkbwjsEVkpqUQIko/SZZCWAPHpEUFStOQoR2UZS3wkzGQ60Kjg/on/G9xxWisfcMDli8ms0KAMH0QWERamiQnXE4XhxWxRQTqh7p/Z1NOyXP78wAbuSMCLGUGi7Kmg5JAlRdAEHBTTxzKXZyzLF1Rdtfx8NoWnE8bF55/PfE=
    - secure: dguHjXv4nm7LQW7TFYWvRYa3f4491+e6yPBnO8KEoY+rho3xk7SDAX85ccspYWCNWUxEe1ED+zcS3o6yxs6Zut8sEBOQYEP605NK7plSUatSL3gEAKntMpD5I4/BQsXlxVvabil39M/qks82JtbPVjJRfryLQVcBiwqSGdTsSehpiZuChNhXsN2FRZZV+n/70TKpee68VRJx5VhEa5xQScfihSxGDUHwbY6ice5oiwB+x3OC3AkPpNIkVtcC1d0bCQl3lA6+W1DvpvT7cNEvmthw6hiq4Ve3eUu8+kdA5K1Odty2Udu2cwNCEqN2kdz6r2FFehmE8tgBCenWWYR8j7hy6ooVYLZNuTNe9wGeMeeC+NyTlUtP9tY266CVpk6lau+L38uXjXkt5VRxXBtTsQnQuUNO319WPkaMbAZoCTgY2nzI7XRmSyfhTX2i9d/HtBKI6/uy2H8WUh33WmV2vmWRydaLvdQ6VHs6r+xSGebv2Mwx4/FIJ3CBn+cj+tcHyCseHdnmI9p/+siiNsdEoNPZTXCsbJ6vl5Hf6xJH1OpuPuyz3Zqcuv3Ea481myW1vc923gX+rvISXrEfiC/Ch6oOXEg9c0aA6SUcmwO6ccAJr5qZraGnjDirF6fINlD1P7E27x+KQ1j2eBJijsUhdLiiG9Wk5FAcG5eTGSXez+M=
    - secure: dM7xMNaqK5Bpkadl1fsjSxNmjmmrT8abNhou63o2yqyZS4T59Z0h6gtbIX+mZxAcIJYcaDCre0w6zGS3x9UPsLpnuGZjMODxqwnKBoQGQhfaJ8N7URLaIJkr0TlYlAng9o+bWRewoDhdWQ43WZeDsBZogGnzgKSWzh0oJYZk9174ePnpSz2flRBni9YMV4slBdoNSz8Zz4+rk6gXeyQX0vAskRx8Ov3EPxKolZxykVeN9qDTwwSrAKir+FY+sZq2c795RpSDISq/p6ZEaKJYinnAfATRuZVvAucaMQ1H+jUZIUWLNe6z8bhBPhiDKem9zcL4YwNDuU3Rpn/EKvnlt29F+iY6cTpBE2af1CNbe1KClBANw9MQGnBx3UhOZGY29Fb812z8Wx1apYoiif2HYoha4y0XIprWXbO7BhL1WW9LQ0FoBwyH21LVunv98GHthUya+VKRBrtcMSdL64yvkEpjXRN1j2pm1h9OUFus01cIZEDzWf7DC/ZokBEEoAEFZEdNvZF83WLDQD1S0ShLJi6mir7t0EXuvbVYENTzqhNJ8FYbog2bB1JaaGWvm2sufInxYozApaY/U6egybJgJ2jqV084WcDQPTCEyJsciRLGQsXkWUAK/fZgan3N6NCzlRzMrL9g/b3Z4p8I6QGm72Ges2FXNVeg3b9yQFYKaiM=

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
  # attention: only repo member can build, contribute user has no permission
  - openssl aes-256-cbc -K $encrypted_171b1c559d7b_key -iv $encrypted_171b1c559d7b_iv -in signingkey.asc.enc -out signingkey.asc -d

before_script:
  - ls -a
  - mvn test -B

deploy:
  - skip_cleanup: true
    provider: script
    script: sh .ci/deploy.sh
    on:
      branch: dev
